import Head from 'next/head';
import { Inter } from '@next/font/google';
import Header from '../components/Header.jsx';
import Footer from '../components/Footer.jsx';
import React, { useState, useEffect } from 'react';
import { NextPage } from 'next';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  const [inputeData, setInputeData] = useState({ Name: '' });

  // console.log(inputeData);

  const fetchData = async () => {
    const response = await fetch(`/api/post/getdata`);
    const json = await response.json();
    setData(json);
    // console.log(json);
  };

  const handleCreateData = async (e: React.FormEvent) => {
    e.preventDefault();
    const response = await fetch(`/api/post/createdata`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        Name: inputeData.Name,
      }),
    });
    const json = await response.json();
    console.log(json);
    setInputeData({ Name: '' });
    fetchData();
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Les Argonautes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="p-10">
        <div>
          <div className="py-5">
            <div className="">
              <div className=" ">
                <h1 className="flex justify-center items-center font-extrabold text-3xl lg:text-2xl py-5">
                  Ajouter un(e) Argonaute
                </h1>

                {/* <!-- New member form --> */}
                <div id="form" className="flex-col justify-center items-center">
                  <form
                    className="flex justify-center items-center space-x-5"
                    onSubmit={handleCreateData}
                  >
                    <label className="px-5">Nom : </label>
                    <input
                      required
                      type="text"
                      id="name"
                      name="name"
                      className="px-2 border-2 border-black rounded-xl"
                      placeholder="Charalampos"
                      value={inputeData.Name}
                      // ou il y a une erreur on peut mettre ce si value={inputeData.Name || ''}
                      onChange={(e) =>
                        setInputeData({ ...inputeData, Name: e.target.value })
                      }
                    />

                    <button
                      type="submit"
                      className="text-white bg-[#665f5f] hover:bg-[#f4f4f4] hover:text-black px-2 border-2 border-black rounded-xl "
                    >
                      Ajouter
                    </button>
                  </form>
                </div>
                <div>
                  <div className="p-10">
                    <h1 className="flex justify-center items-center font-extrabold text-3xl lg:text-2xl py-5">
                      Membres de l&apos;équipage
                    </h1>
                    <div className="flex justify-center items-center ">
                      <table className="border-2 border-black">
                        <thead>
                          <tr>
                            <th className="font-bold text-lg text-center border-2 border-black">
                              Nom
                            </th>
                          </tr>
                        </thead>

                        <tbody className="grid grid-cols-3">
                          {data.map(({ id, Name }) => {
                            return (
                              <tr key={id} className="border-2 ">
                                <td>{Name}</td>
                              </tr>
                            );
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};
export default Home;
